[1.x] Support Laravel 8, Abandon tenancy/testing
tenancy/tenancy pull request #194
Opened 2020-09-15 14:18 UTC by ArlonAntonius

2020-09-15 14:26 UTC, ArlonAntonius commented on .github/workflows/code-style.yml
> -              run: ./vendor/bin/phpcs
Will add this back at some point :)

2020-09-15 14:26 UTC, ArlonAntonius commented on .github/workflows/test.yml
> +                  - laravel: 8.*
L8 Requires PHP >= 7.3

2020-09-15 14:27 UTC, ArlonAntonius commented on .styleci.yml
> +risky: true
Allows StyleCI to add the declare at the top of the file

2020-09-15 14:27 UTC, ArlonAntonius commented on build/tenancy-split.sh
> +# git subsplit publish --heads="master" src/Testing:git@github.com:tenancy/testing.git
Will do this one manually once after release

2020-09-15 14:27 UTC, ArlonAntonius commented on composer.json
> +        "mockery/mockery": "^1.0"
Removed tons of things we don't use anymore

2020-09-15 14:28 UTC, ArlonAntonius commented on src/Testing/Concerns/CreatesApplication.php
> +        });
As we're only using these files internally now, I'm throwing a hard error :)

2020-09-15 14:29 UTC, ArlonAntonius commented on src/Testing/Mocks/Tenant.php
> +    }
Basically:
- Support old factory usage
- Support new factory usage, by copy pasting the hasFactory trait :)

2020-09-16 19:00 UTC, Plytas requested changes

2020-09-16 19:00 UTC, Plytas commented on tests/UsesModels.php
> +            $factory = resolve(Factory::class);
Aren't these 2 the same?

2020-09-17 12:42 UTC, ArlonAntonius commented on tests/UsesModels.php
> +            $factory = resolve(Factory::class);
You are right, will change it asap

2020-09-17 14:09 UTC, Plytas approved these changes, later dismissed

2020-09-17 14:42 UTC, Plytas submitted a review, later dismissed

2020-09-17 15:43 UTC, Plytas approved these changes

2020-09-17 15:44 UTC, fletch3555 approved these changes

2020-09-17 15:47 UTC, merged